# Generated by Django 6.0.1 on 2026-01-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_trackinghistory_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='amount',
            field=models.FloatField(editable=False),
        ),
    ]
