# Generated by Django 6.0.1 on 2026-01-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_requestlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogs',
            name='request_method',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
    ]
