# Generated by Django 6.0.1 on 2026-01-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_requestlogs_request_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='expense_type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=200),
        ),
    ]
